/********************************************************/
/* Wyatt McCurdy                                        */
/* Login ID: wyatt.mccurdy@maine.edu                    */
/* COS 520, Spring 2025                                 */
/* Programming Assignment 6                             */
/* FifteenPlayer class: extends Player class            */
/*           A FifteenPlayer always rolls until         */
/*           it gets to fifteen points                  */
/*      See Kettering University, CS-101, Prog 6        */
/*                                                      */
/* Code generated by GPT 4o                             */
/********************************************************/
 
public class FifteenPlayer extends Player {

    /********************************************************/
    /* Constructor: FifteenPlayer                           */
    /* Purpose: Create a default FifteenPlayer              */
    /* Parameters:                                          */
    /*   none                                               */
    /********************************************************/
    public FifteenPlayer() {
        this("Fifteen");
    }

    /********************************************************/
    /* Constructor: FifteenPlayer                           */
    /* Purpose: Create a new FifteenPlayer object           */
    /* Parameters:                                          */
    /*   String name:  the name of the Player being created */
    /********************************************************/
    public FifteenPlayer(String name) {
        super(name);
    }

    /********************************************************/
    /* Method:  play                                        */
    /* Purpose: Take one turn for this Player               */
    /*          Always rolls until it gets to fifteen       */
    /* Parameters:                                          */
    /*   none                                               */
    /* Returns:                                             */
    /*   the score earned by the player on this turn,       */
    /*       which will be zero if a six was rolled         */
    /********************************************************/
    public int play() {
        int turnScore = 0;

        while (turnScore < 15) {
            int roll = (int) (Math.random() * 6 + 1);
            if (roll == 6) {
                turnScore = 0;
                break;
            } else {
                turnScore += roll;
            }
        }

        setScore(getScore() + turnScore);
        return turnScore;
    }
}