/********************************************************/
/* Wyatt McCurdy                                        */
/* Login ID: wyatt.mccurdy@maine.edu                    */
/* COS 520, Spring 2025                                 */
/* Programming Assignment 6                             */
/* HumanPlayer class: extends Player class              */
/*           A HumanPlayer allows the human to decide   */
/*           whether to roll or end the turn            */
/*      See Kettering University, CS-101, Prog 6        */
/*                                                      */
/* Code generated by GPT 4o                             */
/********************************************************/

/**
 * HumanPlayer class: A player that allows the human to decide whether to roll or end the turn.
 */
public class HumanPlayer extends Player {

    /**
     * Constructor: Creates a default HumanPlayer.
     */
    public HumanPlayer() {
        this("Human");
    }

    /**
     * Constructor: Creates a new HumanPlayer object with the given name.
     * @param name The name of the player being created.
     */
    public HumanPlayer(String name) {
        super(name);
    }

    /**
     * Takes one turn for this player, allowing the human to decide whether to roll or end the turn.
     * @return The score earned by the player on this turn, which will be zero if a six was rolled.
     */
    public int play() {
        int turnScore = 0;
        boolean continueRolling = true;

        while (continueRolling) {
            int roll = (int) (Math.random() * 6 + 1);
            if (roll == 6) {
                turnScore = 0;
                break;
            } else {
                turnScore += roll;
                // The decision to continue rolling will be handled by the UI
                continueRolling = false; // Placeholder, actual decision will be made in the UI
            }
        }

        setScore(getScore() + turnScore);
        return turnScore;
    }
}