package src;
/********************************************************/
/* Wyatt McCurdy                                        */
/* Login ID: wyatt.mccurdy@maine.edu                    */
/* COS 520, Spring 2025                                 */
/* Programming Assignment 6                             */
/* BulldogGame class: Manages the game between two      */
/*           players until one reaches 104 points       */
/*      See Kettering University, CS-101, Prog 6        */
/*                                                      */
/* Code generated by GPT 4o                             */
/********************************************************/

import java.util.Scanner;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class BulldogGame {

    private static final int WINNING_SCORE = 104;
    private Scanner scanner;

    public BulldogGame() {
        scanner = new Scanner(System.in);
    }

    public void startGame() {
        boolean playAgain = true;

        while (playAgain) {
            System.out.println("Welcome to Bulldog Game!");
            Player player1 = selectPlayer(1);
            Player player2 = selectPlayer(2);

            int score1 = 0;
            int score2 = 0;

            while (score1 < WINNING_SCORE && score2 < WINNING_SCORE) {
                System.out.println("\nPlayer 1 (" + player1.getName() + ")'s turn:");
                score1 += player1.play();
                System.out.println("Player 1 (" + player1.getName() + ")'s total score: " + score1);

                if (score1 >= WINNING_SCORE) {
                    System.out.println("\nPlayer 1 (" + player1.getName() + ") wins!");
                    break;
                }

                System.out.println("\nPlayer 2 (" + player2.getName() + ")'s turn:");
                score2 += player2.play();
                System.out.println("Player 2 (" + player2.getName() + ")'s total score: " + score2);

                if (score2 >= WINNING_SCORE) {
                    System.out.println("\nPlayer 2 (" + player2.getName() + ") wins!");
                    break;
                }
            }

            System.out.print("\nWould you like to play again? (y/n): ");
            playAgain = scanner.nextLine().trim().toLowerCase().equals("y");
        }

        System.out.println("Thank you for playing Bulldog Game!");
    }

    private Player selectPlayer(int playerNumber) {
        System.out.println("Select Player " + playerNumber + ":");
        System.out.println("1. WimpPlayer");
        System.out.println("2. RandomPlayer");
        System.out.println("3. FifteenPlayer");
        System.out.println("4. HumanPlayer");
        System.out.println("5. UniquePlayerGPT");
        System.out.println("6. UniquePlayerHuman");
        System.out.print("Enter your choice: ");
        int choice = Integer.parseInt(scanner.nextLine().trim());

        switch (choice) {
            case 1:
                return new WimpPlayer();
            case 2:
                return new RandomPlayer();
            case 3:
                return new FifteenPlayer();
            case 4:
                return new HumanPlayer();
            case 5:
                return new UniquePlayerGPT();
            case 6: 
                return new UniquePlayerHuman();
            default:
                System.out.println("Invalid choice. Defaulting to WimpPlayer.");
                return new WimpPlayer();
        }
    }

    public static void main(String[] args) {
        BulldogGame game = new BulldogGame();
        game.startGame();
    }
}