package src;
/********************************************************/
/* Wyatt McCurdy                                        */
/* Login ID: wyatt.mccurdy@maine.edu                    */
/* COS 520, Spring 2025                                 */
/* Programming Assignment 6                             */
/* HumanPlayer class: extends Player class              */
/*           A HumanPlayer allows the human to decide   */
/*           whether to roll or end the turn            */
/*      See Kettering University, CS-101, Prog 6        */
/*                                                      */
/* Code generated by GPT 4o                             */
/********************************************************/

import java.util.Scanner;

public class HumanPlayer extends Player {

    private Scanner scanner;

    /********************************************************/
    /* Constructor: HumanPlayer                             */
    /* Purpose: Create a default HumanPlayer                */
    /* Parameters:                                          */
    /*   none                                               */
    /********************************************************/
    public HumanPlayer() {
        this("Human");
    }

    /********************************************************/
    /* Constructor: HumanPlayer                             */
    /* Purpose: Create a new HumanPlayer object             */
    /* Parameters:                                          */
    /*   String name:  the name of the Player being created */
    /********************************************************/
    public HumanPlayer(String name) {
        super(name);
        scanner = new Scanner(System.in);
    }

    /********************************************************/
    /* Method:  play                                        */
    /* Purpose: Take one turn for this Player               */
    /*          Allows the human to decide whether to roll  */
    /*          or end the turn                             */
    /* Parameters:                                          */
    /*   none                                               */
    /* Returns:                                             */
    /*   the score earned by the player on this turn,       */
    /*       which will be zero if a six was rolled         */
    /********************************************************/
    public int play() {
        int totalScore = 0;
        boolean continueRolling = true;

        while (continueRolling) {
            int roll = (int) (Math.random() * 6 + 1);
            System.out.print("   Player " + getName() + " rolled " + roll);
            if (roll == 6) {
                totalScore = 0;
                System.out.println(" and scored 0 for the turn.");
                break;
            } else {
                totalScore += roll;
                System.out.println(" and now has a total score of " + totalScore + " for the turn.");
                System.out.print("   Do you want to roll again? (y/n): ");
                String input = scanner.nextLine().trim().toLowerCase();
                continueRolling = input.equals("y");
                if (!continueRolling) {
                    System.out.println("   Player " + getName() + " chose to end the turn with a score of " + totalScore);
                }
            }
        }

        return totalScore;
    }
}