package src;
/********************************************************/
/* Wyatt McCurdy                                        */
/* Login ID: wyatt.mccurdy@maine.edu                    */
/* COS 520, Spring 2025                                 */
/* Programming Assignment 6                             */
/* HumanPlayer class: extends Player class              */
/*           A HumanPlayer allows the human to decide   */
/*           whether to roll or end the turn            */
/*      See Kettering University, CS-101, Prog 6        */
/*                                                      */
/* Code generated by GPT 4o                             */
/********************************************************/

/**
 * HumanPlayer class: A player that allows the human to decide whether to roll or end the turn.
 */
import java.util.Scanner;

public class HumanPlayer extends Player {
    private Scanner scanner = new Scanner(System.in);

    /**
     * Constructor: Creates a default HumanPlayer.
     */
    public HumanPlayer() {
        this("Human");
    }

    /**
     * Constructor: Creates a new HumanPlayer object with the given name.
     * @param name The name of the player being created.
     */
    public HumanPlayer(String name) {
        super(name);
    }

    /**
     * This method will decide whether or not to continue rolling based on the player's input.
     * 
     * @param roll the value of the roll
     * @return boolean result of the roll evaluation
     */
    public boolean evaulate_roll(int roll) {
        // update score
        setTurnScore(getTurnScore() + roll);

        if (roll == 6) {
            setTurnScore(0);
            return false;
        } else {
            return true;
        }
    }
}