package src;
/********************************************************/
/* Wyatt McCurdy                                        */
/* Login ID: wyatt.mccurdy@maine.edu                    */
/* COS 520, Spring 2025                                 */
/* Programming Assignment 6                             */
/* HumanPlayer class: extends Player class              */
/*           A HumanPlayer allows the human to decide   */
/*           whether to roll or end the turn            */
/*      See Kettering University, CS-101, Prog 6        */
/*                                                      */
/* Code generated by GPT 4o                             */
/********************************************************/

/**
 * HumanPlayer class: A player that allows the human to decide whether to roll or end the turn.
 */
import java.util.Scanner;

public class HumanPlayer extends Player {
    private Scanner scanner = new Scanner(System.in);
    private int turnScore;

    /**
     * Constructor: Creates a default HumanPlayer.
     */
    public HumanPlayer() {
        this("Human");
    }

    /**
     * Constructor: Creates a new HumanPlayer object with the given name.
     * @param name The name of the player being created.
     */
    public HumanPlayer(String name) {
        super(name);
    }

    /**
     * Takes one turn for this player, allowing the human to decide whether to roll or end the turn.
     * @return The score earned by the player on this turn, which will be zero if a six was rolled.
     */
    public int play() {
        int totalScore = 0;
        System.out.println("Would you like to roll? (y/n)?");

        boolean continueRolling = true;

        String input = scanner.nextLine().trim().toLowerCase();
        continueRolling = input.equals("y");

        while (continueRolling) {
            int roll = (int) (Math.random() * 6 + 1);
            if (roll == 6) {
                turnScore = 0;
                break;
            } else {
                totalScore += roll;
                System.out.println(" and now has a total score of " + totalScore + " for the turn.");
                System.out.print("   Do you want to roll again? (y/n): ");
                input = scanner.nextLine().trim().toLowerCase();
                continueRolling = input.equals("y");
                if (!continueRolling) {
                    System.out.println("   Player " + getName() + " chose to end the turn with a score of " + totalScore);
                }
            }
        }

        setScore(getScore() + turnScore);
        return turnScore;
    }
}