package src;
/********************************************************/
/* Wyatt McCurdy                                        */
/* Login ID: wyatt.mccurdy@maine.edu                    */
/* COS 520, Spring 2025                                 */
/* Programming Assignment 6                             */
/* RandomPlayer class: extends Player class             */
/*           A RandomPlayer randomly decides whether    */
/*           to roll or end the turn                    */
/*      See Kettering University, CS-101, Prog 6        */
/*                                                      */
/* Code generated by GPT 4o                             */
/********************************************************/

public class RandomPlayer extends Player {

    /********************************************************/
    /* Constructor: RandomPlayer                            */
    /* Purpose: Create a default RandomPlayer               */
    /* Parameters:                                          */
    /*   none                                               */
    /********************************************************/
    public RandomPlayer() {
        this("Random");
    }

    /********************************************************/
    /* Constructor: RandomPlayer                            */
    /* Purpose: Create a new RandomPlayer object            */
    /* Parameters:                                          */
    /*   String name:  the name of the Player being created */
    /********************************************************/
    public RandomPlayer(String name) {
        super(name);
    }

    /**
     * This method will decide whether or not to continue rolling based on a random decision.
     */
    public boolean evaulate_roll(int roll) {
        boolean continuing = true;
        // update score
        setTurnScore(getTurnScore() + roll);

        if (roll == 6) {
            setTurnScore(0);
            return false;
        } else {
            continuing =  Math.random() < 0.5; // 50/50 chance to continue rolling
        }

        if (continuing == false) {
            setScore(getScore() + getTurnScore());
            return false;
        } else { return true; }
    }

    /********************************************************/
    /* Method:  play                                        */
    /* Purpose: Take one turn for this Player               */
    /*          Randomly decides whether to roll or end     */
    /* Parameters:                                          */
    /*   none                                               */
    /* Returns:                                             */
    /*   the score earned by the player on this turn,       */
    /*       which will be zero if a six was rolled         */
    /********************************************************/
    public int play() {
        setTurnScore(0);
        boolean continueRolling = true;

        while (continueRolling) {
            int roll = (int) (Math.random() * 6 + 1);
            continueRolling = evaulate_roll(roll);
        }

        setScore(getScore() + getTurnScore());
        return getTurnScore();
    }
}