package src;
/********************************************************/
/* Wyatt McCurdy                                        */
/* Login ID: wyatt.mccurdy@maine.edu                    */
/* COS 520, Spring 2025                                 */
/* Programming Assignment 6                             */
/* RandomPlayer class: extends Player class             */
/*           A RandomPlayer randomly decides whether    */
/*           to roll or end the turn                    */
/*      See Kettering University, CS-101, Prog 6        */
/*                                                      */
/* Code generated by GPT 4o                             */
/********************************************************/

public class RandomPlayer extends Player {

    /********************************************************/
    /* Constructor: RandomPlayer                            */
    /* Purpose: Create a default RandomPlayer               */
    /* Parameters:                                          */
    /*   none                                               */
    /********************************************************/
    public RandomPlayer() {
        this("Random");
    }

    /********************************************************/
    /* Constructor: RandomPlayer                            */
    /* Purpose: Create a new RandomPlayer object            */
    /* Parameters:                                          */
    /*   String name:  the name of the Player being created */
    /********************************************************/
    public RandomPlayer(String name) {
        super(name);
    }

    /********************************************************/
    /* Method:  play                                        */
    /* Purpose: Take one turn for this Player               */
    /*          Randomly decides whether to roll or end     */
    /* Parameters:                                          */
    /*   none                                               */
    /* Returns:                                             */
    /*   the score earned by the player on this turn,       */
    /*       which will be zero if a six was rolled         */
    /********************************************************/
    public int play() {
        int turnScore = 0;
        boolean continueRolling = true;

        while (continueRolling) {
            int roll = (int) (Math.random() * 6 + 1);
            if (roll == 6) {
                turnScore = 0;
                break;
            } else {
                turnScore += roll;
                continueRolling = Math.random() < 0.5; // 50/50 chance to continue rolling
            }
        }

        setScore(getScore() + turnScore);
        return turnScore;
    }
}