package src;
/********************************************************/
/* Wyatt McCurdy                                        */
/* Login ID: wyatt.mccurdy@maine.edu                    */
/* COS 520, Spring 2025                                 */
/* Programming Assignment 6                             */
/* UniquePlayerGPT class: extends Player class          */
/*           A UniquePlayerGPT uses a unique strategy   */
/*           to maximize the score                      */
/*      See Kettering University, CS-101, Prog 6        */
/*                                                      */
/* Code generated by GPT 4o                             */
/********************************************************/

public class UniquePlayerGPT extends Player {

    /********************************************************/
    /* Constructor: UniquePlayerGPT                         */
    /* Purpose: Create a default UniquePlayerGPT            */
    /* Parameters:                                          */
    /*   none                                               */
    /********************************************************/
    public UniquePlayerGPT() {
        this("UniqueGPT");
    }

    /********************************************************/
    /* Constructor: UniquePlayerGPT                         */
    /* Purpose: Create a new UniquePlayerGPT object         */
    /* Parameters:                                          */
    /*   String name:  the name of the Player being created */
    /********************************************************/
    public UniquePlayerGPT(String name) {
        super(name);
    }

    /********************************************************/
    /* Method:  play                                        */
    /* Purpose: Take one turn for this Player               */
    /*          Uses a unique strategy to maximize score    */
    /* Parameters:                                          */
    /*   none                                               */
    /* Returns:                                             */
    /*   the score earned by the player on this turn,       */
    /*       which will be zero if a six was rolled         */
    /********************************************************/
    public int play() {
        int totalScore = 0;

        while (totalScore < 10) {
            int roll = (int) (Math.random() * 6 + 1);
            System.out.print("   Player " + getName() + " rolled " + roll);
            if (roll == 6) {
                totalScore = 0;
                System.out.println(" and scored 0 for the turn.");
                break;
            } else {
                totalScore += roll;
                System.out.println(" and now has a total score of " + totalScore + " for the turn.");
                if (roll >= 4) {
                    System.out.println("   Player " + getName() + " stops rolling with a score of " + totalScore);
                    break;
                }
            }
        }

        if (totalScore >= 10) {
            System.out.println("   Player " + getName() + " reached or exceeded 10 points and ends the turn with a score of " + totalScore);
        }

        return totalScore;
    }
}