/********************************************************/
/* Wyatt McCurdy                                        */
/* COS 520, Spring 2025                                 */
/* Bulldog Game                                         */
/* RandomPlayer class: extends Player class             */
/*           A RandomPlayer always decides based on     */
/*           a 50/50 coin flip                          */
/********************************************************/

public class RandomPlayer extends Player {

	/********************************************************/
	/* Constructor: RandomPlayer                            */
	/* Purpose: Create a default RandomPlayer               */
	/* Parameters:                                          */
	/*   none                                               */
	/********************************************************/
	public RandomPlayer () {
		this("Random");
	}

	/********************************************************/
	/* Constructor: RandomPlayer                            */
	/* Purpose: Create a new RandomPlayer object            */
	/* Parameters:                                          */
	/*   String name:  the name of the Player being created */
	/********************************************************/
	public RandomPlayer (String name) {
		super(name);
	}

	/********************************************************/
	/* Method:  play                                        */
	/* Purpose: Take one turn for this Player               */
	/*          One turn for a RandomPlayer is however many */
	/*          turns are generated by random coin flip     */
	/* Parameters:                                          */
	/*   none                                               */
	/* Returns:                                             */
	/*   the score earned by the player on this turn,       */
	/*       which will be zero if a six was rolled         */
	/********************************************************/
	public int play() {

		// Initialize score
        int turn_score = 0;
        float doIPlay = (float) (Math.random());
        while (doIPlay > 0.5) {
            int roll = (int) (Math.random()*6 + 1);
            if (roll != 6) {
				turn_score = turn_score + roll;
                System.out.println(getName() + " rolled a " + roll + " for a turn score of " + turn_score + ".");
                doIPlay = (float) (Math.random());
            } else {
                turn_score = 0;
                System.out.println(getName() + " rolled a 6 and scored 0 points for the turn.");
				System.out.println(getName() + " currently has " + getScore() + " points.");
				return 0;
            }
        }

		int cur_score = getScore();
		cur_score = cur_score + turn_score;
		setScore(cur_score);

		System.out.println(getName() + " scored " + turn_score + " points this round.");
		System.out.println(getName() + " has " + getScore() + " total points.");
		return turn_score;
	}
}
